### PR TITLE
Kb product location search

### PR DESCRIPTION
**Pull request by klboyd**
# Description
Adds product type view and adds customer serializer to products

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
# Testing Instructions
1. `git fetch --all`
1. `git checkout kb-product-location-search`
1. do fetch on product and see customer in response

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works
- [x] My functions have doc strings

### CODE REVIEW

**Comment by klboyd** [comment]
aaaaahhhhhhhhhhhhh

**Review by laurenriddle — COMMENTED** [review]
🐒 + 🐓= 🌮

**Review by laurenriddle — DISMISSED** [review]

**Review by RyanCrowleyCode — APPROVED** [review]
I'm good, you're good, we all scream for ice cream.

**Review by laurenriddle — APPROVED** [review]

**Comment by klboyd** [comment]
ahhhhhhhhhhhhhhhhhh

**Pull request merged**
